I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 389, in script
    define s = Character(server_name, color='f2d0ea', image='server chan')
  File "game/script.rpy", line 389, in <module>
    define s = Character(server_name, color='f2d0ea', image='server chan')
NameError: name 'server_name' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 389, in script
    define s = Character(server_name, color='f2d0ea', image='server chan')
  File "renpy/ast.py", line 2508, in execute
    self.set()
  File "renpy/ast.py", line 2522, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "renpy/python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 389, in <module>
    define s = Character(server_name, color='f2d0ea', image='server chan')
NameError: name 'server_name' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 7.6.3.23091805
О_моем_перерождении_в_сервер 3.0
Tue Nov 28 11:09:00 2023
